
// --------------------------------------------------------------------------------------------------
//	This code was generated by the ETLA Toolbelt Wizard version 1.0.59.11
//	Generated date: 2021-Mar-04 16:30:31
//
//	Changes to this file will be lost if the code is regenerated.
//	To make changes or additions, rerun the ETLA Toolbelt Wizard after editing T4 templates if required
// --------------------------------------------------------------------------------------------------

namespace GenericJsonSuite.EtlaToolbelt.Contexts;

/// <summary>This defines the properties and methods that relate to the running context of an application
/// Note to implementors:
///  The methods defined here must never throw an exception
/// </summary>
public interface IContext
{
    /// <summary>The name of the environment the application is running in (e.g. "DEV")</summary>
    string Env { get; set; }

    /// <summary>The name of the application</summary>
    string App { get; set; }

    /// <summary>The name of the account running the application</summary>
    string UserName { get; }

    /// <summary>The "domain" part of the full name of the account running the application</summary>
	string UserDomain { get; }

    /// <summary>Reports on whether the environment the application is running in is a "development" environment (e.g. on a programmers machine)</summary>
    /// <returns><c>true</c> if the environment appears to be a development environment; <c>false</c> otherwise</returns>
	bool IsDev();

    /// <summary>Reports on whether the environment the application is running in is a "production" environment (i.e. not development or test, but live)</summary>
    /// <returns><c>true</c> if the environment appears to be a production environment; <c>false</c> otherwise</returns>
	bool IsProduction();
}
