// --------------------------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by the ETLA Toolbelt Wizard version 1.0.59.11
//	Generated date: 2021-Mar-04 16:30:31
//
//	Changes to this file will be lost if the code is regenerated.
//	To make changes or additions, rerun the ETLA Toolbelt Wizard after editing T4 templates if required
// </auto-generated>
// --------------------------------------------------------------------------------------------------

namespace GenericJsonSuite.EtlaToolbelt.Logs;

/// <summary>>This defines the properties and methods that targets for log messages must provide and expose
/// Note to implementors:
///  The methods defined here must never throw an exception
/// </summary>
public interface ILogSink
{
    /// <summary>Defines which messages are sent to the sink and which are ignored
    /// <see cref="LogLevel"/> for further details (but note that this is a set of flags and not an integer)
    /// </summary>
    LogLevel LevelToShow { get; set; }

    /// <summary>Returns true if a log message with this LogLevel is sent or ignored</summary>
    /// <param name="level">The LogLevel of a message</param>
    /// <returns><c>true</c> if a log message with this LogLevel is to be sent; <c>false</c> otherwise</returns>
    bool Shows(LogLevel level);

    /// <summary>Writes the log message to the sink's medium</summary>
    /// <param name="logMessage">The log message to write</param>
    void Write(LogMessage logMessage);

    /// <summary>Translates a structured LogMessage into a string relevant for this sink meduim</summary>
    /// <param name="logMessage">The log message to format</param>
    /// <returns>The string containing the formatted log message</returns>
    string Format(LogMessage logMessage);
}