// --------------------------------------------------------------------------------------------------
//	This code was generated by the ETLA Toolbelt Wizard version 1.0.59.11
//	Generated date: 2021-Mar-04 16:30:31
//
//	Changes to this file will be lost if the code is regenerated.
//	To make changes or additions, rerun the ETLA Toolbelt Wizard after editing T4 templates if required
// --------------------------------------------------------------------------------------------------
// ReSharper disable InconsistentNaming
namespace GenericJsonSuite.EtlaToolbelt.Logs;

/// <summary>The flag-based enum which specifies different types of log message
/// </summary>
[Flags]
public enum LogLevel
{
    /// <summary>No log message.  The default.  No actual log message should have this value</summary>
    NONE = 0,

    /// <summary>Debugging level message</summary>
    DEBUG = 1 << 1,
    /// <summary>Informational level message</summary>
    INFO = 1 << 2,
    /// <summary>Warning level message</summary>
    WARN = 1 << 3,
    /// <summary>Error level message</summary>
    ERROR = 1 << 4,
    /// <summary>Fatal error level message</summary>
    FATAL = 1 << 5,

    /// <summary>Level indicating the application has started</summary>
    START = 1 << 8,
    /// <summary>Level indicating the application has finished</summary>
    FINISH = 1 << 9,


    /// <summary>Used by sinks which are only interested in the most high level messages</summary>
    SHOW_FATAL = FATAL | START,
    /// <summary>Used by sinks which are only interested in the error level or higher messages</summary>
    SHOW_ERROR = ERROR | FINISH | SHOW_FATAL,
    /// <summary>Used by sinks which are only interested in the warning level or higher messages</summary>
    SHOW_WARN = WARN | SHOW_ERROR,
    /// <summary>Used by sinks which are only interested in the informational level or higher messages</summary>
    SHOW_INFO = INFO | SHOW_WARN,
    /// <summary>Used by sinks which are interested all messages</summary>
    SHOW_DEBUG = DEBUG | SHOW_INFO,
}